"""rename address

Revision ID: 84396368ca9a
Revises: c1c8f9c1e30e
Create Date: 2024-07-18 01:33:05.269724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84396368ca9a'
down_revision = 'c1c8f9c1e30e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###